// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDjIXX6HD_gAVcitJ60No7igr_mzUzsc',
    appId: '1:969710943806:web:43137567d9a1b33b7bdb6f',
    messagingSenderId: '969710943806',
    projectId: 'mobileappdevelopment-215be',
    authDomain: 'mobileappdevelopment-215be.firebaseapp.com',
    storageBucket: 'mobileappdevelopment-215be.firebasestorage.app',
    measurementId: 'G-4Z2S450K3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_CHt1YiwjpJisE0Eu8P9ArAuWZKX2hBM',
    appId: '1:969710943806:android:5094f8014ac547a87bdb6f',
    messagingSenderId: '969710943806',
    projectId: 'mobileappdevelopment-215be',
    storageBucket: 'mobileappdevelopment-215be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFzggO5Xqwsj7f15RsgSFNF8Yavvpzswg',
    appId: '1:969710943806:ios:3dd1fb10ce72e87e7bdb6f',
    messagingSenderId: '969710943806',
    projectId: 'mobileappdevelopment-215be',
    storageBucket: 'mobileappdevelopment-215be.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFzggO5Xqwsj7f15RsgSFNF8Yavvpzswg',
    appId: '1:969710943806:ios:3dd1fb10ce72e87e7bdb6f',
    messagingSenderId: '969710943806',
    projectId: 'mobileappdevelopment-215be',
    storageBucket: 'mobileappdevelopment-215be.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjDjIXX6HD_gAVcitJ60No7igr_mzUzsc',
    appId: '1:969710943806:web:4db779eff2440bc27bdb6f',
    messagingSenderId: '969710943806',
    projectId: 'mobileappdevelopment-215be',
    authDomain: 'mobileappdevelopment-215be.firebaseapp.com',
    storageBucket: 'mobileappdevelopment-215be.firebasestorage.app',
    measurementId: 'G-70RZE2KVKD',
  );
}
